### ISSUE TITLE
custom_transport example (unix domain sockets)

### ISSUE THREAD

**Issue by createyourpersonalaccount** [google/tarpc#363]
I'm trying to use [examples/custom_transport.rs](https://github.com/google/tarpc/blob/master/tarpc/examples/custom_transport.rs) in a project, but I get the error

 ```
error[E0432]: unresolved import `tarpc::tokio_serde::formats`
```

I can't find `tokio_serde` anywhere in the docs. What is it and how do I enable it? My toml file is this,

```toml
[package]
name = "tarpc_example"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
futures = "0.3"
tarpc = { version = "0.27", features = ["tokio1"] }
tokio = { version = "1", features = ["time", "macros"] }
tarpc-plugins = { version = "0.12", optional = true }
tokio-serde = { version = "0.8", optional = true }
tokio-util = { version = "0.6.3", features = ["time"], optional = true }
serde = { version = "1.0", optional = true }

[features]
unix_socket-feats = ["tokio/net", "tokio/rt", "tokio-serde", "tokio-util/codec", "tarpc/serde-transport", "tarpc-plugins/serde1", "serde", "serde/derive"]

[[bin]]
name = "unix_socket"
required-features = ["unix_socket-feats"]
```
